---
settings:
  name: BlueXP cloud ops
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: BlueXP Cloud-Ops-Dokumente
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
  - title: Los geht's
    entries:
    - title: Mehr zu BlueXP Cloud Ops
      url: "/concept-compute.html"
    - title: Verbinden Sie Ihr AWS Konto
      url: "/task-getting-started-compute.html"
  - title: Analysieren Sie Ihre Computing-Kosten
    url: "/task-analyze-costs.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
